version = 0.1
[default.deploy.parameters]
stack_name = "mhc-frontpage"
resolve_s3 = true
s3_prefix = "mhc-frontpage"
region = "eu-central-1"
profile = "mhc"
capabilities = "CAPABILITY_IAM"
image_repositories = []
