AWSTemplateFormatVersion: 2010-09-09
Description: >-
  mhc-frontpage
Transform:
- AWS::Serverless-2016-10-31

Resources:
  MHCFrontPageCFDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: !Sub 's3-origin-${MHCFrontpageBucket}'
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          AllowedMethods: [GET, HEAD, OPTIONS]
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCachingMinTTL: 86400
            ErrorCode: 403 # object not found in bucket
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 86400
            ErrorCode: 404 # object not found in bucket
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - DomainName: !GetAtt MHCFrontpageBucket.DomainName
            Id: !Sub 's3-origin-${MHCFrontpageBucket}'
            OriginPath: ''
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CFOriginAccessIdentity}'


  # the s3 bucket with the static webpage
  MHCFrontpageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'mhc-frontpage-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CFOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'

  # policy to allow the cloudfront distribution to access the s3 bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the bucket'
    Properties:
      Bucket: !Ref MHCFrontpageBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CFOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${MHCFrontpageBucket}/*'

